WORKERS_TOTAL = '1'
PRICE_SOLD = '2'
PRICE_NOT_SOLD = '3'
PRICE_TOTAL = '4'
AMOUNT_SOLD = '5'
AMOUNT_NOT_SOLD = '6'
AMOUNT_TOTAL = '7'

WORKERS_TOTAL_LABEL = 'Количество работников'
PRICE_SOLD_LABEL = 'Сумма проданных товаров'
PRICE_NOT_SOLD_LABEL = 'Сумма непроданных товаров'
PRICE_TOTAL_LABEL = 'Суммарная стоимость товаров'
AMOUNT_SOLD_LABEL = 'Количество проданных товаров'
AMOUNT_NOT_SOLD_LABEL = 'Количество непроданных товаров'
AMOUNT_TOTAL_LABEL = 'Суммарное количество товаров'
