# Generated by Django 2.1.7 on 2019-03-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(max_length=30, verbose_name='Сфера деятельности')),
                ('staff_amount', models.IntegerField(verbose_name='Кол-во сотрудников департамента')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название магазина')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес магазина')),
                ('staff_amount', models.IntegerField(verbose_name='Кол-во сотрудников магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Департаменты', to='main.Shop', verbose_name='Магазин'),
        ),
    ]
